### ISSUE TITLE
Missing parameter in “az apic service create -h” Examples

### ISSUE THREAD

**Issue by ayachensiyuan** [blackchoey/azure-cli-extensions#23]
### Describe the bug

<img width="1211" alt="image" src="https://github.com/blackchoey/azure-cli-extensions/assets/67082457/4dd8b513-84a5-45e8-a62d-cd38166ebef5">
missing "service" in command

### Related command

az apic service create -h

### Errors

'create' is misspelled or not recognized by the system.

### Issue script & Debug output

az apic service create -h

### Expected behavior

no error message

### Environment Summary

azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Extensions:
apic-extension                   1.0.0b5

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/Cellar/azure-cli/2.59.0/libexec/bin/python'
Extensions directory '/Users/chensiyuan/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by ayachensiyuan** [comment]
same issue in "az apic list -h" and "az apic update -h"

**Comment by hellyzh** [comment]
![image](https://github.com/blackchoey/azure-cli-extensions/assets/49181894/c56e6200-56a8-40ad-a773-e28eee6d7275)
missing a single quote `'`

**Comment by ayachensiyuan** [comment]
Verification passed
