### ISSUE TITLE
Getting ValidationError for the Sku property is null running az apic service update

### ISSUE THREAD

**Issue by hellyzh** [blackchoey/azure-cli-extensions#25]
### Describe the bug

![image](https://github.com/blackchoey/azure-cli-extensions/assets/49181894/2640336d-65d2-45b9-ae0d-e71569af009d)

### Related command

az apic service update -g hlytest424 --name hlyservice424c --tags '{test:value}' --identity '{type:SystemAssigned}'

### Errors

(ValidationError) The Sku property on the given model is null. A valid Sku is required to create or update an API Catalog.
Code: ValidationError
Message: The Sku property on the given model is null. A valid Sku is required to create or update an API Catalog.

### Issue script & Debug output

az apic service create -g hlytest424 --name hlyservice424c --tags '{test:value}' --identity '{type:SystemAssigned}'
(ValidationError) The Sku property on the given model is null. A valid Sku is required to create or update an API Catalog.
Code: ValidationError
Message: The Sku property on the given model is null. A valid Sku is required to create or update an API Catalog.

### Expected behavior

Pass

### Environment Summary

azure cli 2.49
apic_extension-1.0.0b5-py3-none-any

**Comment by juliajuju93** [comment]
This seems to be an issue with --identity

![image](https://github.com/blackchoey/azure-cli-extensions/assets/42241691/2ee6eb49-f647-47fb-9d9e-8b74641bbf36)

**Comment by blackchoey** [comment]
Workaround by using PATCH request.

**Comment by hellyzh** [comment]
Verified
