### ISSUE TITLE
missing parameter "--assignments" In "az apic metadata create" Examples command 

### ISSUE THREAD

**Issue by ayachensiyuan** [blackchoey/azure-cli-extensions#26]
### Describe the bug

missing parameter "--assignments" In "az apic metadata create" Examples command 
<img width="1250" alt="image" src="https://github.com/blackchoey/azure-cli-extensions/assets/67082457/92790a74-d456-4b22-b439-4bccac9a86a7">
<img width="1626" alt="image" src="https://github.com/blackchoey/azure-cli-extensions/assets/67082457/f4ec8ef2-4be6-4d3a-a971-b068a1ed7e3f">

### Related command

az apic metadata create --resource-group ivan-testapi-rg --service-name service-01 --name "test1" --schema '{"type":"string", "title":"First name", "pattern": "^[a-zA-Z0-9]+$"}'

### Errors

the following arguments are required: --assignments

### Issue script & Debug output

az apic metadata create --resource-group ivan-testapi-rg --service-name service-01 --name "test1" --schema '{"type":"string", "title":"First name", "pattern": "^[a-zA-Z0-9]+$"}'
the following arguments are required: --assignments

### Expected behavior

no error

### Environment Summary

azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Extensions:
apic-extension                   1.0.0b5

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/Cellar/azure-cli/2.59.0/libexec/bin/python'
Extensions directory '/Users/chensiyuan/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by alisa-1020** [comment]
az appeared twice in update/create/delete/show -h 
<img width="879" alt="image" src="https://github.com/blackchoey/azure-cli-extensions/assets/77324688/ad15e602-73f9-49ea-bc53-84e60ea05d51">

**Comment by juliajuju93** [comment]
Yes, --assignments is requiered as mentioned in -help
![image](https://github.com/blackchoey/azure-cli-extensions/assets/42241691/20eb2592-2f43-4a69-b159-f400cb44ba68)

I would recommend we update the Examples here.

**Comment by ayachensiyuan** [comment]
<img width="1266" alt="image" src="https://github.com/blackchoey/azure-cli-extensions/assets/67082457/fc6d19ca-111b-4d2e-8fd9-1af83c0eaea3">
missing '  in  "az apic service import-from-apim -h" Examples

**Comment by ayachensiyuan** [comment]
Verification passed
